global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'

rule_files:
  - 'alert.rules.yml'

scrape_configs:
  - job_name: 'fastapi'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8000']